# Generated by Django 3.2.4 on 2021-08-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='questions',
        ),
    ]
