# Generated by Django 3.2.4 on 2021-08-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_article_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
