# Generated by Django 3.2.4 on 2021-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questions_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('giuld', models.CharField(max_length=200)),
                ('pack', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
