# Generated by Django 3.2.4 on 2021-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='pack',
            field=models.IntegerField(default=1),
        ),
    ]
